name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  MIX_ENV: test
  SECRET_KEY_BASE_SR: ${{ secrets.SECRET_KEY_BASE_SR }}
  LIVE_VIEW_SALT_SR: ${{ secrets.LIVE_VIEW_SALT_SR }}
  SIGNING_SALT_SR: ${{ secrets.SIGNING_SALT_SR }}

jobs:
  pipeline:
    name: Pipeline
    runs-on: ubuntu-latest
    services:
      db:
        image: postgres:latest
        ports: [ '5432:5432' ]
        env:
          POSTGRES_PASSWORD: postgres
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5
    strategy:
      fail-fast: false
      matrix:
        elixir: [ 1.11 ]
        otp: [ 23.2 ]
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup
        uses: actions/setup-elixir@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}
          experimental-otp: true
      - name: Retrieve Cached Dependencies
        uses: actions/cache@v2
        id: mix-cache
        with:
          path: |
            deps
            _build
            priv/plts
          key: ${{ runner.os }}-${{ matrix.otp }}-${{ matrix.elixir }}-${{ hashFiles('mix.lock') }}
      - name: Install Dependencies
        if: steps.mix-cache.outputs.cache-hit != 'true'
        run: |
          mkdir -p priv/plts
          mix local.rebar --force
          mix local.hex --force
          mix deps.get
          mix deps.compile
          mix compile --force
      - name: Run test
        run: mix test --trace --slowest 10
